### ISSUE TITLE
Exporter reports Exim as down, even though service is running 

### ISSUE THREAD

**Issue by shobhitrawat** [gvengel/exim_exporter#11] opened 2022-08-30 07:19 UTC
I am getting the same issue even though I am using the latest version of exim exporter 1.4.1.

I am running the docker image of Exim with the below configuration.

docker-compose.yml
version: '3'
services:
  smtp:
    build: .
    image: smtp
    volumes:
       - /var/log/exim4:/var/log/exim4
       - /var/spool/exim4:/var/spool/exim4
    container_name: smtp
    restart: always
    ports:
      - "25:25"

Dockerfile

FROM ubuntu:18.04

RUN apt-get update && apt-get -y install telnet net-tools vim exim4 && chmod 777 -R /var/log/exim4 && chown -R root:root /var/log/exim4/

COPY ./update-exim4.conf.conf /etc/exim4/update-exim4.conf.conf
COPY ./passwd.client /etc/exim4/passwd.client
COPY ./exim4.conf.template /etc/exim4/exim4.conf.template
COPY ./02_exim4-config_options /etc/exim4/conf.d/main/02_exim4-config_options

EXPOSE 25
CMD ["/etc/init.d/exim4", "start"]

exim --version
Exim version 4.90_1 https://github.com/gvengel/exim_exporter/issues/4 built 30-Apr-2021 14:15:04
Copyright (c) University of Cambridge, 1995 - 2017

ps -ewF| grep exim
root 1 0 0 1159 1884 11 Aug26 ? 00:00:00 /bin/sh /etc/init.d/exim4 start
Debian-+ 263 1 0 15388 6584 23 Aug26 ? 00:00:44 /usr/sbin/exim4 -bd -q30m

The exporter is running with the following parameters:

sudo docker run \
-p 9636:9636
-v /var/log/exim4:/var/log/exim4
-v /var/spool/exim4:/var/spool/exim4
-e exim.executable='exim4'
--pid container:'smtp'
--name exim_exporter
gvengel/exim_exporter

ts=2022-08-30T05:48:56.268Z caller=main.go:360 level=info msg="Starting exim exporter" version="(version=1.4.1, branch=HEAD, revision=4b465da)"
ts=2022-08-30T05:48:56.268Z caller=main.go:361 level=info msg="Build context" context="(go=go1.19, user=, date=)"
ts=2022-08-30T05:48:56.268Z caller=main.go:250 level=info msg="Opening log" filename=/var/log/exim4/mainlog
ts=2022-08-30T05:48:56.268Z caller=main.go:250 level=info msg="Opening log" filename=/var/log/exim4/rejectlog
ts=2022-08-30T05:48:56.268Z caller=main.go:250 level=info msg="Opening log" filename=/var/log/exim4/paniclog
ts=2022-08-30T05:48:56.269Z caller=main.go:401 level=info msg=Listening address=:9636
ts=2022-08-30T05:48:56.269Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
ts=2022-08-30T05:48:56.269Z caller=log.go:198 ts="2022/08/30 05:48:56" caller="Seeked /var/log/exim4/mainlog - &{Offset:0" msg=" Whence:2}"
ts=2022-08-30T05:48:56.269Z caller=log.go:198 ts="2022/08/30 05:48:56" caller="Seeked /var/log/exim4/rejectlog - &{Offset:0" msg=" Whence:2}"
ts=2022-08-30T05:48:56.269Z caller=log.go:198 ts="2022/08/30 05:48:56" caller="Seeked /var/log/exim4/paniclog - &{Offset:0" msg=" Whence:2}"

curl -L localhost:9636/metrics | grep exim_up
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0# HELP exim_up Whether or not the main exim daemon is running

TYPE exim_up gauge
exim_up 0
100 18351 0 18351 0 0 943k 0 --:--:-- --:--:-- --:--:-- 943k

**Comment by gvengel** [comment] 2022-08-30 16:52
Thanks for the report @shobhitrawat. If possible, can you update your message to use code blocks where applicable? I can probably translate where github has converted YAML to markdown, but better to avoid confusion. 

Either way, I'll try to reproduce the issue this evening.

**Comment by shobhitrawat** [comment] 2022-08-30 17:02
@gvengel  updated, let me know if you need more details.

**Comment by gvengel** [comment] 2023-07-01 06:54
Closing this as I have been unable to reproduce the issue. Happy to reopen if you can provide full instructions. Perhaps a single docker compose file which pulls all the required containers including configs. e.g. 
```
# docker compose up -d
...
# curl -s localhost:9636/metrics | grep -E '^exim_up'
exim_up 0
# 
```

Another option would be to put all the configs in a temp git repository I can clone to reproduce.

Thanks.

**Closed by gvengel** 2023-07-01 06:54 UTC
